version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Expose port 80 from the container to port 3000 on your machine (React app will run here)
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000" # Expose backend API on port 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
