version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Expose port 3000 for React's development server
    volumes:
      - ./frontend:/app  # Mount local code to container for live reloading
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker for better reloading performance
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Expose backend API on port 5000
    volumes:
      - ./backend:/app  # Mount the backend code for live development
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
